package ast.c;

import ast.AbstractSyntaxTree;
import org.eclipse.cdt.core.dom.ast.IASTNode;
import org.eclipse.cdt.core.dom.ast.IASTPreprocessorMacroDefinition;
import org.eclipse.cdt.core.dom.ast.IASTTranslationUnit;
import org.eclipse.cdt.internal.core.dom.parser.c.*;

import java.util.HashMap;

/**
 * Name:        EclipseCDT2Internal.java
 * Content:     This class is in charge of translating the AST corresponding to the C program generated by Eclipse-CDT
 * 				into its (equivalent) internal representation using the elements in "src/java/ast/c".
 * Author:      Quentin Nivon
 * Email:       quentin.nivon@uol.de
 * Creation:    26/03/26
 */

public class EclipseCDT2Internal
{
	//Constructors

	private EclipseCDT2Internal()
	{

	}

	//Public methods

	public static AbstractSyntaxTree translate(final IASTTranslationUnit translationUnit)
	{
		/*
			(Temporary) fix for macro expansion that we want to avoid.
			The translation now basically compares the literal values against the ones in the map and replaces them if
			they correspond.
			Caution: this may introduce undesired behaviours when the program contains original non-expanded literals
			with the same value as an existing macro, as it will consequently be "unexpanded".
			This does not affect the semantics of the C program, but will change its syntax.
			This fix is nonetheless probably rather useful to preserve the syntax of the original C program.
			TODO find a way to avoid macro expansion during parsing!
		 */
		final HashMap<String, String> expandedValue2Macro = new HashMap<>();

		for (final IASTPreprocessorMacroDefinition macroDefinition : translationUnit.getMacroDefinitions())
		{
			expandedValue2Macro.put(macroDefinition.getExpansion(), macroDefinition.getName().toString());
		}

		final AbstractSyntaxTree abstractSyntaxTree = new AbstractSyntaxTree(CFactory.createTranslationUnitNode());
		EclipseCDT2Internal.translate(translationUnit, (CBaseNode) abstractSyntaxTree.getRoot(), expandedValue2Macro);
		abstractSyntaxTree.collapse();
		
		return abstractSyntaxTree;
	}

	//Private methods

	public static void translate(final IASTNode eclipseCdtNode,
								 final CBaseNode internalNode,
								 final HashMap<String, String> expandedValue2Macro)
	{
		for (final IASTNode iastNode : eclipseCdtNode.getChildren())
		{
			final CBaseNode correspondingInternalNode;

			if (iastNode instanceof CASTArraySubscriptExpression)
			{
				correspondingInternalNode = CFactory.createArraySubscriptExpressionNode();
			}
			else if (iastNode instanceof CASTBinaryExpression)
			{
				correspondingInternalNode = CFactory.createBinaryExpressionNode(((CASTBinaryExpression) iastNode).getOperator());
			}
			else if (iastNode instanceof CASTCompoundStatement)
			{
				correspondingInternalNode = CFactory.createCompoundStatementNode();
			}
			else if (iastNode instanceof CASTDeclarationStatement)
			{
				correspondingInternalNode = CFactory.createDeclarationStatementNode();
			}
			else if (iastNode instanceof CASTFunctionDeclarator)
			{
				correspondingInternalNode = CFactory.createFunctionDeclaratorNode();
			}
			else if (iastNode instanceof CASTDeclarator)
			{
				correspondingInternalNode = CFactory.createDeclaratorNode();
			}
			else if (iastNode instanceof CASTExpressionStatement)
			{
				correspondingInternalNode = CFactory.createExpressionStatementNode();
			}
			else if (iastNode instanceof CASTForStatement)
			{
				correspondingInternalNode = CFactory.createForStatementNode();
			}
			else if (iastNode instanceof CASTFunctionCallExpression)
			{
				correspondingInternalNode = CFactory.createFunctionCallExpressionNode();
			}
			else if (iastNode instanceof CASTFunctionDefinition)
			{
				correspondingInternalNode = CFactory.createFunctionDefinitionNode();
			}
			else if (iastNode instanceof CASTIdExpression)
			{
				correspondingInternalNode = CFactory.createIdExpressionNode();
			}
			else if (iastNode instanceof CASTIfStatement)
			{
				correspondingInternalNode = CFactory.createIfStatementNode();
			}
			else if (iastNode instanceof CASTLiteralExpression)
			{
				final String literalValue = expandedValue2Macro.getOrDefault(iastNode.toString(), iastNode.toString());
				correspondingInternalNode = CFactory.createLiteralExpressionNode(literalValue);
			}
			else if (iastNode instanceof CASTName)
			{
				correspondingInternalNode = CFactory.createNameNode(iastNode.toString());
			}
			else if (iastNode instanceof CASTParameterDeclaration)
			{
				correspondingInternalNode = CFactory.createParameterDeclarationNode();
			}
			else if (iastNode instanceof CASTPointer)
			{
				correspondingInternalNode = CFactory.createPointerNode();
			}
			else if (iastNode instanceof CASTReturnStatement)
			{
				correspondingInternalNode = CFactory.createReturnStatementNode();
			}
			else if (iastNode instanceof CASTSimpleDeclaration)
			{
				correspondingInternalNode = CFactory.createSimpleDeclarationNode();
			}
			else if (iastNode instanceof CASTSimpleDeclSpecifier)
			{
				correspondingInternalNode = CFactory.createSimpleDeclarationSpecifierNode(
					((CASTSimpleDeclSpecifier) iastNode).getStorageClass(),
					((CASTSimpleDeclSpecifier) iastNode).getType(),
					((CASTSimpleDeclSpecifier) iastNode).isConst(),
					((CASTSimpleDeclSpecifier) iastNode).isInline(),
					((CASTSimpleDeclSpecifier) iastNode).isRestrict(),
					((CASTSimpleDeclSpecifier) iastNode).isVolatile()
				);
			}
			else if (iastNode instanceof CASTTypedefNameSpecifier)
			{
				correspondingInternalNode = CFactory.createTypedefNameSpecifierNode(
					((CASTTypedefNameSpecifier) iastNode).getStorageClass(),
					((CASTTypedefNameSpecifier) iastNode).isConst(),
					((CASTTypedefNameSpecifier) iastNode).isInline(),
					((CASTTypedefNameSpecifier) iastNode).isRestrict(),
					((CASTTypedefNameSpecifier) iastNode).isVolatile(),
					((CASTTypedefNameSpecifier) iastNode).getName().toString()
				);
			}
			else if (iastNode instanceof CASTUnaryExpression)
			{
				correspondingInternalNode = CFactory.createUnaryExpressionNode(
					((CASTUnaryExpression) iastNode).getOperator()
				);
			}
			else
			{
				throw new UnsupportedOperationException(String.format("Node %s type is unknown!", iastNode.toString()));
			}

			internalNode.addChildAndForceParent(correspondingInternalNode);
			EclipseCDT2Internal.translate(iastNode, correspondingInternalNode, expandedValue2Macro);
		}
	}
}
