package ast.c;

import ast.AbstractSyntaxTree;
import dto.CComment;
import org.eclipse.cdt.core.dom.ast.IASTNode;
import org.eclipse.cdt.core.dom.ast.IASTPreprocessorMacroDefinition;
import org.eclipse.cdt.core.dom.ast.IASTTranslationUnit;
import org.eclipse.cdt.internal.core.dom.parser.c.*;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Name:        EclipseCDT2Internal.java
 * Content:     This class is in charge of translating the AST corresponding to the C program generated by Eclipse-CDT
 * 				into its (equivalent) internal representation using the elements in "src/java/ast/c".
 * Author:      Quentin Nivon
 * Email:       quentin.nivon@uol.de
 * Creation:    26/03/26
 */

public class EclipseCDT2Internal
{
	//Constructors

	private EclipseCDT2Internal()
	{

	}

	//Public methods

	public static AbstractSyntaxTree translate(final IASTTranslationUnit translationUnit,
	                                           final Map<IASTNode, List<CComment>> nodeToCommentsMapping)
	{
		/*
			(Temporary) fix for macro expansion that we want to avoid.
			The translation now basically compares the literal values against the ones in the map and replaces them if
			they correspond.
			Caution: this may introduce undesired behaviours when the program contains original non-expanded literals
			with the same value as an existing macro, as it will consequently be "unexpanded".
			This does not affect the semantics of the C program, but will change its syntax.
			This fix is nonetheless probably rather useful to preserve the syntax of the original C program.
			TODO find a way to avoid macro expansion during parsing!
		 */
		final HashMap<String, String> expandedValue2Macro = new HashMap<>();

		for (final IASTPreprocessorMacroDefinition macroDefinition : translationUnit.getMacroDefinitions())
		{
			expandedValue2Macro.put(macroDefinition.getExpansion(), macroDefinition.getName().toString());
		}

		final AbstractSyntaxTree abstractSyntaxTree = new AbstractSyntaxTree(CFactory.createTranslationUnitNode());
		EclipseCDT2Internal.translate(
			translationUnit,
			(CBaseNode) abstractSyntaxTree.getRoot(),
			expandedValue2Macro,
			nodeToCommentsMapping
		);
		abstractSyntaxTree.collapse();
		
		return abstractSyntaxTree;
	}

	//Private methods

	private static void translate(final IASTNode eclipseCdtNode,
	                              final CBaseNode internalNode,
	                              final HashMap<String, String> expandedValue2Macro,
	                              final Map<IASTNode, List<CComment>> nodeToCommentsMapping)
	{
		for (final IASTNode iastNode : eclipseCdtNode.getChildren())
		{
			final CBaseNode correspondingInternalNode;

			if (iastNode instanceof CASTArrayDeclarator)
			{
				correspondingInternalNode = CFactory.createArrayDeclaratorNode();
			}
			else if (iastNode instanceof CASTArrayModifier)
			{
				correspondingInternalNode = CFactory.createArrayModifierNode();
			}
			else if (iastNode instanceof CASTArraySubscriptExpression)
			{
				correspondingInternalNode = CFactory.createArraySubscriptExpressionNode();
			}
			else if (iastNode instanceof CASTBinaryExpression)
			{
				correspondingInternalNode = CFactory.createBinaryExpressionNode(((CASTBinaryExpression) iastNode).getOperator());
			}
			else if (iastNode instanceof CASTCompoundStatement)
			{
				correspondingInternalNode = CFactory.createCompoundStatementNode();
			}
			else if (iastNode instanceof CASTDeclarationStatement)
			{
				correspondingInternalNode = CFactory.createDeclarationStatementNode();
			}
			else if (iastNode instanceof CASTFunctionDeclarator)
			{
				correspondingInternalNode = CFactory.createFunctionDeclaratorNode();
			}
			else if (iastNode instanceof CASTDeclarator)
			{
				correspondingInternalNode = CFactory.createDeclaratorNode();
			}
			else if (iastNode instanceof CASTExpressionStatement)
			{
				correspondingInternalNode = CFactory.createExpressionStatementNode();
			}
			else if (iastNode instanceof CASTForStatement)
			{
				correspondingInternalNode = CFactory.createForStatementNode();
			}
			else if (iastNode instanceof CASTFunctionCallExpression)
			{
				correspondingInternalNode = CFactory.createFunctionCallExpressionNode();
			}
			else if (iastNode instanceof CASTFunctionDefinition)
			{
				correspondingInternalNode = CFactory.createFunctionDefinitionNode();
			}
			else if (iastNode instanceof CASTIdExpression)
			{
				correspondingInternalNode = CFactory.createIdExpressionNode();
			}
			else if (iastNode instanceof CASTIfStatement)
			{
				correspondingInternalNode = CFactory.createIfStatementNode();
			}
			else if (iastNode instanceof CASTLiteralExpression)
			{
				final String literalValue = expandedValue2Macro.getOrDefault(iastNode.toString(), iastNode.toString());
				correspondingInternalNode = CFactory.createLiteralExpressionNode(literalValue);
			}
			else if (iastNode instanceof CASTName)
			{
				correspondingInternalNode = CFactory.createNameNode(iastNode.toString());
			}
			else if (iastNode instanceof CASTParameterDeclaration)
			{
				correspondingInternalNode = CFactory.createParameterDeclarationNode();
			}
			else if (iastNode instanceof CASTPointer)
			{
				correspondingInternalNode = CFactory.createPointerNode();
			}
			else if (iastNode instanceof CASTReturnStatement)
			{
				correspondingInternalNode = CFactory.createReturnStatementNode();
			}
			else if (iastNode instanceof CASTSimpleDeclaration)
			{
				correspondingInternalNode = CFactory.createSimpleDeclarationNode();
			}
			else if (iastNode instanceof CASTSimpleDeclSpecifier)
			{
				correspondingInternalNode = CFactory.createSimpleDeclarationSpecifierNode(
					((CASTSimpleDeclSpecifier) iastNode).getStorageClass(),
					((CASTSimpleDeclSpecifier) iastNode).getType(),
					((CASTSimpleDeclSpecifier) iastNode).isConst(),
					((CASTSimpleDeclSpecifier) iastNode).isInline(),
					((CASTSimpleDeclSpecifier) iastNode).isRestrict(),
					((CASTSimpleDeclSpecifier) iastNode).isVolatile()
				);
			}
			else if (iastNode instanceof CASTTypedefNameSpecifier)
			{
				correspondingInternalNode = CFactory.createTypedefNameSpecifierNode(
					((CASTTypedefNameSpecifier) iastNode).getStorageClass(),
					((CASTTypedefNameSpecifier) iastNode).isConst(),
					((CASTTypedefNameSpecifier) iastNode).isInline(),
					((CASTTypedefNameSpecifier) iastNode).isRestrict(),
					((CASTTypedefNameSpecifier) iastNode).isVolatile(),
					((CASTTypedefNameSpecifier) iastNode).getName().toString()
				);
			}
			else if (iastNode instanceof CASTUnaryExpression)
			{
				correspondingInternalNode = CFactory.createUnaryExpressionNode(
					((CASTUnaryExpression) iastNode).getOperator()
				);
			}
			else if (iastNode instanceof CASTNullStatement)
			{
				correspondingInternalNode = CFactory.createNullStatementNode();
			}
			else if (iastNode instanceof CASTEqualsInitializer)
			{
				correspondingInternalNode = CFactory.createEqualsInitializerNode();
			}
			else if (iastNode instanceof CASTCompositeTypeSpecifier)
			{
				correspondingInternalNode = CFactory.createCompositeTypeSpecifierNode(((CASTCompositeTypeSpecifier) iastNode).getStorageClass());
			}
			else if (iastNode instanceof CASTCastExpression)
			{
				correspondingInternalNode = CFactory.createCastExpressionNode();
			}
			else if (iastNode instanceof CASTTypeId)
			{
				correspondingInternalNode = CFactory.createTypeIdNode();
			}
			else if (iastNode instanceof CASTElaboratedTypeSpecifier)
			{
				correspondingInternalNode = CFactory.createElaboratedTypeSpecifierNode(
					((CASTElaboratedTypeSpecifier) iastNode).getKind()
				);
			}
			else if (iastNode instanceof CASTTypeIdExpression)
			{
				correspondingInternalNode = CFactory.createTypeIdExpressionNode();
			}
			else if (iastNode instanceof CASTFieldReference)
			{
				correspondingInternalNode = CFactory.createFieldReferenceNode();
			}
			else if (iastNode instanceof CASTLabelStatement)
			{
				correspondingInternalNode = CFactory.createLabelStatementNode();
			}
			else if (iastNode instanceof CASTGotoStatement)
			{
				correspondingInternalNode = CFactory.createGotoStatementNode();
			}
			else if (iastNode instanceof CASTWhileStatement)
			{
				correspondingInternalNode = CFactory.createWhileStatementNode();
			}
			else
			{
				throw new UnsupportedOperationException(String.format("Node type \"%s\" is unknown!", iastNode.toString()));
			}

			if (nodeToCommentsMapping.containsKey(iastNode))
			{
				correspondingInternalNode.addComments(nodeToCommentsMapping.get(iastNode));
			}

			internalNode.addChildAndForceParent(correspondingInternalNode);
			EclipseCDT2Internal.translate(iastNode, correspondingInternalNode, expandedValue2Macro, nodeToCommentsMapping);
		}
	}
}
