package ast.acsl;

import ast.AbstractSyntaxNode;
import constants.acsl.others.AcslType;
import misc.Utils;

/**
 * Name:        OperatorNode.java
 * Content:	    This class defines an OperatorNode containing the name (i.e., a string) of the considered operator as
 * 				defined in the XML file generated by SYNTAX.
 * 				Note that this node is not supposed to remain in the final abstract syntax tree generated, as method
 * 				AbstractSyntaxTree.collapse() should remove it from the tree.
 * 				It is only used as a helper for the parsing of the SYNTAX-generated XML file.
 * Author:      Quentin Nivon
 * Email:       quentin.nivon@uol.de
 * Creation:    17/03/26
 */

public class OperatorNode extends AcslBaseNode
{
	private String name;

	//Constructors

	public OperatorNode()
	{
		this(null);
	}

	public OperatorNode(final String name)
	{
		super(AcslType.OPERATOR);
		this.name = name;
	}

	//Overrides

	@Override
	public void stringify(final StringBuilder builder,
						  final int depth)
	{
		builder.append("\n")
				.append(Utils.repeatTabs(depth))
				.append(String.format("- Operator \"%s\" has ", this.name == null ? null : this.name));

		if (this.getChildren().isEmpty())
		{
			builder.append("no child.");
		}
		else if (this.getChildren().size() == 1)
		{
			builder.append("1 child:");
			this.getChildren().iterator().next().stringify(builder, depth + 1);
		}
		else
		{
			builder.append(String.format("%d children:", this.getChildren().size()));

			for (final AbstractSyntaxNode child : this.getChildren())
			{
				child.stringify(builder, depth + 1);
			}
		}
	}

	@Override
	public String checkWellFormedness()
	{
		if (this.name == null
			|| this.name.isEmpty())
		{
			return "Operator node is malformed: it should have a non-null non-empty name.";
		}

		return null;
	}

	//Public methods

	public void setName(final String name)
	{
		this.name = name;
	}

	public String getName()
	{
		return this.name;
	}
}
