package constants.c;

import org.eclipse.cdt.core.dom.ast.IASTBinaryExpression;

/**
 * Name:        CBinaryOperator.java
 * Content:	    This enum defines the binary operators supported by Eclipse-CDT and/or ACSL along with their actual
 * 				(textual) representation, their XML representation as generated by SYNTAX, and some utility methods
 * 				useful for converting the Eclipse-CDT types to these operators and conversely.
 * Author:      Quentin Nivon
 * Email:       quentin.nivon@uol.de
 * Creation:    26/02/26
 */

public enum CBinaryOperator
{
	ASSIGNMENT("=", null, IASTBinaryExpression.op_assign),
	BINARY_AND("&", "band", IASTBinaryExpression.op_binaryAnd),
	BINARY_AND_ASSIGNMENT("&=", null, IASTBinaryExpression.op_binaryAndAssign),
	BINARY_EQUIVALENCE("<-->", "bequiv", -1),
	BINARY_IMPLICATION("-->", "bimp", -1),
	BINARY_OR("|", "bor", IASTBinaryExpression.op_binaryOr),
	BINARY_OR_ASSIGNMENT("|=", null, IASTBinaryExpression.op_binaryOrAssign),
	BINARY_XOR("^", "bxor", IASTBinaryExpression.op_binaryXor),
	BINARY_XOR_ASSIGNMENT("^=", null, IASTBinaryExpression.op_binaryXorAssign),
	DIVIDE("/", "div", IASTBinaryExpression.op_divide),
	DIVIDE_ASSIGNMENT("/=", null, IASTBinaryExpression.op_divideAssign),
	ELLIPSES("...", null, IASTBinaryExpression.op_ellipses),
	EQUALS("==", "eq", IASTBinaryExpression.op_equals),
	GREATER_OR_EQUAL(">=", "geq", IASTBinaryExpression.op_greaterEqual),
	GREATER_THAN(">", "gt", IASTBinaryExpression.op_greaterThan),
	LESS_OR_EQUAL("<=", "leq", IASTBinaryExpression.op_lessEqual),
	LESS_THAN("<", "lt", IASTBinaryExpression.op_lessThan),
	LIST_REPETITION("*^", "lr",-1),
	LOGICAL_AND("&&", "land", IASTBinaryExpression.op_logicalAnd),
	LOGICAL_EQUIVALENCE("<==>", "lequiv", -1),
	LOGICAL_IMPLICATION("==>", "limp", -1),
	LOGICAL_OR("||", "lor", IASTBinaryExpression.op_logicalOr),
	LOGICAL_XOR("^^", "lxor", -1),
	MINUS("-", "min", IASTBinaryExpression.op_minus),
	MINUS_ASSIGNMENT("-=", null, IASTBinaryExpression.op_minusAssign),
	MODULO("%", "mod", IASTBinaryExpression.op_modulo),
	MODULO_ASSIGNMENT("%=", null, IASTBinaryExpression.op_moduloAssign),
	MULTIPLY("*", "mul", IASTBinaryExpression.op_multiply),
	MULTIPLY_ASSIGNMENT("*=", null, IASTBinaryExpression.op_multiplyAssign),
	NOT_EQUALS("!=", "neq", IASTBinaryExpression.op_notequals),
	PLUS("+", "add", IASTBinaryExpression.op_plus),
	PLUS_ASSIGNMENT("+=", null, IASTBinaryExpression.op_plusAssign),
	SHIFT_LEFT("<<", "lshift", IASTBinaryExpression.op_shiftLeft),
	SHIFT_LEFT_ASSIGNMENT("<<=", null, IASTBinaryExpression.op_shiftLeftAssign),
	SHIFT_RIGHT(">>", "rshift", IASTBinaryExpression.op_shiftRight),
	SHIFT_RIGHT_ASSIGNMENT(">>=", null, IASTBinaryExpression.op_shiftRightAssign)
	;

	private final String operator;
	private final String xmlName;
	private final int eclipseCDTIntValue;

	//Constructors

	CBinaryOperator(final String operator,
					final String xmlName,
					final int eclipseCDTIntValue)
	{
		this.operator = operator;
		this.xmlName = xmlName;
		this.eclipseCDTIntValue = eclipseCDTIntValue;
	}

	//Overrides

	@Override
	public String toString()
	{
		return this.operator;
	}

	//Public functions

	public String getOperator()
	{
		return this.operator;
	}

	public String getXmlName()
	{
		return this.xmlName;
	}

	public int getEclipseCDTIntValue()
	{
		return this.eclipseCDTIntValue;
	}

	//Static functions

	public static CBinaryOperator convertEclipseCDTBinaryOperatorToThis(final int eclipseCDTBinaryOperatorInt)
	{
		switch (eclipseCDTBinaryOperatorInt)
		{
			case IASTBinaryExpression.op_assign:
			{
				return CBinaryOperator.ASSIGNMENT;
			}

			case IASTBinaryExpression.op_binaryAnd:
			{
				return CBinaryOperator.BINARY_AND;
			}

			case IASTBinaryExpression.op_binaryAndAssign:
			{
				return CBinaryOperator.BINARY_AND_ASSIGNMENT;
			}

			case IASTBinaryExpression.op_binaryOr:
			{
				return CBinaryOperator.BINARY_OR;
			}

			case IASTBinaryExpression.op_binaryOrAssign:
			{
				return CBinaryOperator.BINARY_OR_ASSIGNMENT;
			}

			case IASTBinaryExpression.op_binaryXor:
			{
				return CBinaryOperator.BINARY_XOR;
			}

			case IASTBinaryExpression.op_binaryXorAssign:
			{
				return CBinaryOperator.BINARY_XOR_ASSIGNMENT;
			}

			case IASTBinaryExpression.op_divide:
			{
				return CBinaryOperator.DIVIDE;
			}

			case IASTBinaryExpression.op_divideAssign:
			{
				return CBinaryOperator.DIVIDE_ASSIGNMENT;
			}

			case IASTBinaryExpression.op_ellipses:
			{
				return CBinaryOperator.ELLIPSES;
			}

			case IASTBinaryExpression.op_equals:
			{
				return CBinaryOperator.EQUALS;
			}

			case IASTBinaryExpression.op_greaterEqual:
			{
				return CBinaryOperator.GREATER_OR_EQUAL;
			}

			case IASTBinaryExpression.op_greaterThan:
			{
				return CBinaryOperator.GREATER_THAN;
			}

			case IASTBinaryExpression.op_lessEqual:
			{
				return CBinaryOperator.LESS_OR_EQUAL;
			}

			case IASTBinaryExpression.op_lessThan:
			{
				return CBinaryOperator.LESS_THAN;
			}

			case IASTBinaryExpression.op_logicalAnd:
			{
				return CBinaryOperator.LOGICAL_AND;
			}

			case IASTBinaryExpression.op_logicalOr:
			{
				return CBinaryOperator.LOGICAL_OR;
			}

			case IASTBinaryExpression.op_minus:
			{
				return CBinaryOperator.MINUS;
			}

			case IASTBinaryExpression.op_minusAssign:
			{
				return CBinaryOperator.MINUS_ASSIGNMENT;
			}

			case IASTBinaryExpression.op_modulo:
			{
				return CBinaryOperator.MODULO;
			}

			case IASTBinaryExpression.op_moduloAssign:
			{
				return CBinaryOperator.MODULO_ASSIGNMENT;
			}

			case IASTBinaryExpression.op_multiply:
			{
				return CBinaryOperator.MULTIPLY;
			}

			case IASTBinaryExpression.op_multiplyAssign:
			{
				return CBinaryOperator.MULTIPLY_ASSIGNMENT;
			}

			case IASTBinaryExpression.op_notequals:
			{
				return CBinaryOperator.NOT_EQUALS;
			}

			case IASTBinaryExpression.op_plus:
			{
				return CBinaryOperator.PLUS;
			}

			case IASTBinaryExpression.op_plusAssign:
			{
				return CBinaryOperator.PLUS_ASSIGNMENT;
			}

			case IASTBinaryExpression.op_shiftLeft:
			{
				return CBinaryOperator.SHIFT_LEFT;
			}

			case IASTBinaryExpression.op_shiftLeftAssign:
			{
				return CBinaryOperator.SHIFT_LEFT_ASSIGNMENT;
			}

			case IASTBinaryExpression.op_shiftRight:
			{
				return CBinaryOperator.SHIFT_RIGHT;
			}

			case IASTBinaryExpression.op_shiftRightAssign:
			{
				return CBinaryOperator.SHIFT_RIGHT_ASSIGNMENT;
			}

			default:
			{
				throw new UnsupportedOperationException(
					String.format(
						"The Eclipse-CDT binary operator of value |%d| is not handled yet.",
						eclipseCDTBinaryOperatorInt
					)
				);
			}
		}
	}

	public static CBinaryOperator convertXmlOperatorNameToThis(final String xmlName)
	{
		if (xmlName.equals(CBinaryOperator.MULTIPLY.getXmlName()))
		{
			return CBinaryOperator.MULTIPLY;
		}
		else if (xmlName.equals(CBinaryOperator.DIVIDE.getXmlName()))
		{
			return CBinaryOperator.DIVIDE;
		}
		else if (xmlName.equals(CBinaryOperator.MODULO.getXmlName()))
		{
			return CBinaryOperator.MODULO;
		}
		else if (xmlName.equals(CBinaryOperator.PLUS.getXmlName()))
		{
			return CBinaryOperator.PLUS;
		}
		else if (xmlName.equals(CBinaryOperator.MINUS.getXmlName()))
		{
			return CBinaryOperator.MINUS;
		}
		else if (xmlName.equals(CBinaryOperator.SHIFT_LEFT.getXmlName()))
		{
			return CBinaryOperator.SHIFT_LEFT;
		}
		else if (xmlName.equals(CBinaryOperator.SHIFT_RIGHT.getXmlName()))
		{
			return CBinaryOperator.SHIFT_RIGHT;
		}
		else if (xmlName.equals(CBinaryOperator.LESS_THAN.getXmlName()))
		{
			return CBinaryOperator.LESS_THAN;
		}
		else if (xmlName.equals(CBinaryOperator.LESS_OR_EQUAL.getXmlName()))
		{
			return CBinaryOperator.LESS_OR_EQUAL;
		}
		else if (xmlName.equals(CBinaryOperator.GREATER_THAN.getXmlName()))
		{
			return CBinaryOperator.GREATER_THAN;
		}
		else if (xmlName.equals(CBinaryOperator.GREATER_OR_EQUAL.getXmlName()))
		{
			return CBinaryOperator.GREATER_OR_EQUAL;
		}
		else if (xmlName.equals(CBinaryOperator.EQUALS.getXmlName()))
		{
			return CBinaryOperator.EQUALS;
		}
		else if (xmlName.equals(CBinaryOperator.NOT_EQUALS.getXmlName()))
		{
			return CBinaryOperator.NOT_EQUALS;
		}
		else if (xmlName.equals(CBinaryOperator.BINARY_AND.getXmlName()))
		{
			return CBinaryOperator.BINARY_AND;
		}
		else if (xmlName.equals(CBinaryOperator.LIST_REPETITION.getXmlName()))
		{
			return CBinaryOperator.LIST_REPETITION;
		}
		else if (xmlName.equals(CBinaryOperator.BINARY_XOR.getXmlName()))
		{
			return CBinaryOperator.BINARY_XOR;
		}
		else if (xmlName.equals(CBinaryOperator.BINARY_OR.getXmlName()))
		{
			return CBinaryOperator.BINARY_OR;
		}
		else if (xmlName.equals(CBinaryOperator.BINARY_IMPLICATION.getXmlName()))
		{
			return CBinaryOperator.BINARY_IMPLICATION;
		}
		else if (xmlName.equals(CBinaryOperator.BINARY_EQUIVALENCE.getXmlName()))
		{
			return CBinaryOperator.BINARY_EQUIVALENCE;
		}
		else if (xmlName.equals(CBinaryOperator.LOGICAL_AND.getXmlName()))
		{
			return CBinaryOperator.LOGICAL_AND;
		}
		else if (xmlName.equals(CBinaryOperator.LOGICAL_XOR.getXmlName()))
		{
			return CBinaryOperator.LOGICAL_XOR;
		}
		else if (xmlName.equals(CBinaryOperator.LOGICAL_OR.getXmlName()))
		{
			return CBinaryOperator.LOGICAL_OR;
		}
		else if (xmlName.equals(CBinaryOperator.LOGICAL_IMPLICATION.getXmlName()))
		{
			return CBinaryOperator.LOGICAL_IMPLICATION;
		}
		else if (xmlName.equals(CBinaryOperator.LOGICAL_EQUIVALENCE.getXmlName()))
		{
			return CBinaryOperator.LOGICAL_EQUIVALENCE;
		}
		else
		{
			throw new UnsupportedOperationException(
				String.format("The ACSL operator \"%s\" is not handled yet.", xmlName)
			);
		}
	}
}
