package constants.c;

import org.eclipse.cdt.core.dom.ast.IASTUnaryExpression;

/**
 * Name:        CUnaryOperator.java
 * Content:	    This enum defines the unary operators supported by Eclipse-CDT and/or ACSL along with their actual
 * 				(textual) representation, their XML representation as generated by SYNTAX, and some utility methods
 * 				useful for converting the Eclipse-CDT types to these operators and conversely.
 * Author:      Quentin Nivon
 * Email:       quentin.nivon@uol.de
 * Creation:    26/02/26
 */

public enum CUnaryOperator
{
	ADDRESS("&", "addr", IASTUnaryExpression.op_amper, true),
	BRACKETS("()", null, IASTUnaryExpression.op_bracketedPrimary, true),
	COMPLEMENT("~", "compl", IASTUnaryExpression.op_tilde, true),
	INDIRECTION("*", "indi", IASTUnaryExpression.op_star, true),
	MINUS("-", "neg", IASTUnaryExpression.op_minus, true),
	NOT("!", "not", IASTUnaryExpression.op_not, true),
	PLUS("+", "pos", IASTUnaryExpression.op_plus, true),
	POSTFIX_DECREMENTATION("--", null, IASTUnaryExpression.op_postFixDecr, false),
	POSTFIX_INCREMENTATION("++", null, IASTUnaryExpression.op_postFixIncr, false),
	PREFIX_DECREMENTATION("--", null, IASTUnaryExpression.op_prefixDecr, true),
	PREFIX_INCREMENTATION("++", null, IASTUnaryExpression.op_prefixIncr, true),
	SIZEOF("sizeof", null, IASTUnaryExpression.op_sizeof, true)
	;

	private final String operator;
	private final String xmlName;
	private final int eclipseCDTIntValue;
	private final boolean isPrefixOperator;

	//Constructors

	CUnaryOperator(final String operator,
				   final String xmlName,
				   final int eclipseCDTIntValue,
				   final boolean isPrefixOperator)
	{
		this.operator = operator;
		this.xmlName = xmlName;
		this.eclipseCDTIntValue = eclipseCDTIntValue;
		this.isPrefixOperator = isPrefixOperator;
	}

	//Public functions

	public String getOperator()
	{
		return this.operator;
	}

	public String getXmlName()
	{
		return this.xmlName;
	}

	public int getEclipseCDTIntValue()
	{
		return this.eclipseCDTIntValue;
	}

	public boolean isPrefixOperator()
	{
		return this.isPrefixOperator;
	}

	//Static functions

	public static CUnaryOperator convertEclipseCDTUnaryOperatorToThis(final int eclipseCDTUnaryOperatorInt)
	{
		switch (eclipseCDTUnaryOperatorInt)
		{
			case IASTUnaryExpression.op_amper:
			{
				return CUnaryOperator.ADDRESS;
			}

			case IASTUnaryExpression.op_minus:
			{
				return CUnaryOperator.MINUS;
			}

			case IASTUnaryExpression.op_not:
			{
				return CUnaryOperator.NOT;
			}

			case IASTUnaryExpression.op_plus:
			{
				return CUnaryOperator.PLUS;
			}

			case IASTUnaryExpression.op_postFixDecr:
			{
				return CUnaryOperator.POSTFIX_DECREMENTATION;
			}

			case IASTUnaryExpression.op_postFixIncr:
			{
				return CUnaryOperator.POSTFIX_INCREMENTATION;
			}

			case IASTUnaryExpression.op_prefixDecr:
			{
				return CUnaryOperator.PREFIX_DECREMENTATION;
			}

			case IASTUnaryExpression.op_prefixIncr:
			{
				return CUnaryOperator.PREFIX_INCREMENTATION;
			}

			case IASTUnaryExpression.op_sizeof:
			{
				return CUnaryOperator.SIZEOF;
			}

			case IASTUnaryExpression.op_star:
			{
				return CUnaryOperator.INDIRECTION;
			}

			case IASTUnaryExpression.op_tilde:
			{
				return CUnaryOperator.COMPLEMENT;
			}

			case IASTUnaryExpression.op_bracketedPrimary:
			{
				return CUnaryOperator.BRACKETS;
			}

			case IASTUnaryExpression.op_throw:
			case IASTUnaryExpression.op_typeid:
			case IASTUnaryExpression.op_sizeofParameterPack:
			case IASTUnaryExpression.op_noexcept:
			case IASTUnaryExpression.op_integerPack:
			{
				throw new UnsupportedOperationException(
					String.format(
						"The Eclipse-CDT unary operator of value |%d| is reserved to C++ programs!",
						eclipseCDTUnaryOperatorInt
					)
				);
			}

			default:
			{
				throw new UnsupportedOperationException(
					String.format(
						"The Eclipse-CDT unary operator of value |%d| is not handled yet.",
						eclipseCDTUnaryOperatorInt
					)
				);
			}
		}
	}

	public static CUnaryOperator convertXmlOperatorNameToThis(final String xmlName)
	{
		if (xmlName.equals(CUnaryOperator.PLUS.getXmlName()))
		{
			return CUnaryOperator.PLUS;
		}
		else if (xmlName.equals(CUnaryOperator.MINUS.getXmlName()))
		{
			return CUnaryOperator.MINUS;
		}
		else if (xmlName.equals(CUnaryOperator.NOT.getXmlName()))
		{
			return CUnaryOperator.NOT;
		}
		else if (xmlName.equals(CUnaryOperator.COMPLEMENT.getXmlName()))
		{
			return CUnaryOperator.COMPLEMENT;
		}
		else if (xmlName.equals(CUnaryOperator.INDIRECTION.getXmlName()))
		{
			return CUnaryOperator.INDIRECTION;
		}
		else if (xmlName.equals(CUnaryOperator.ADDRESS.getXmlName()))
		{
			return CUnaryOperator.ADDRESS;
		}
		else
		{
			throw new UnsupportedOperationException(
				String.format("The ACSL operator \"%s\" is not handled yet.", xmlName)
			);
		}
	}
}
