package constants.acsl.xml;

/**
 * Name:        AcslXmlAttribute.java
 * Content:	    This class defines all the attributes contained in the XML file generated by SYNTAX as a result of
 * 				parsing an ACSL comment.
 * Author:      Quentin Nivon
 * Email:       quentin.nivon@uol.de
 * Creation:    16/03/26
 */

public class AcslXmlAttribute
{
	private AcslXmlAttribute()
	{

	}

	public static final String KIND = "kind";
}
