package constants.acsl.xml;

/**
 * Name:        AcslXmlTag.java
 * Content:	    This class defines all the tags contained in the XML file generated by SYNTAX as a result of parsing
 * 				an ACSL comment.
 * Author:      Quentin Nivon
 * Email:       quentin.nivon@uol.de
 * Creation:    16/03/26
 */

public class AcslXmlTag
{
	private AcslXmlTag()
	{

	}

	public static final String ACSL_FILE = "acslfile";
	public static final String FUNCTION_CONTRACT = "function-contract";
	public static final String OPERATOR = "op";
	public static final String PREDICATE_OR_TERM = "predicate-or-term";
	public static final String REQUIRES_CLAUSE = "requires";
	public static final String REQUIRES_CLAUSE_LIST = REQUIRES_CLAUSE + "-clause-list";
}
