package constants.acsl.xml;

/**
 * Name:        AcslXmlOperator.java
 * Content:	    This class defines all the operators contained in the XML file generated by SYNTAX as a result of
 * 				parsing an ACSL comment.
 * Author:      Quentin Nivon
 * Email:       quentin.nivon@uol.de
 * Creation:    16/03/26
 */

public class AcslXmlOperator
{
	private AcslXmlOperator()
	{

	}

	public static final String EQUALS = "eq";
	public static final String GREATER_OR_EQUALS = "geq";
	public static final String GREATER_THAN = "gt";
	public static final String LOWER_OR_EQUALS = "leq";
	public static final String LOWER_THAN = "lt";
}
