package acsl_to_c;

import ast.AbstractSyntaxTree;
import ast.c.CBaseNode;
import ast.c.CFactory;
import ast.c.CompositeTypeSpecifierNode;
import constants.c.CCommentNature;
import constants.c.CCommentType;
import constants.c.CStorageClass;
import constants.c.CType;
import dto.CComment;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Name:        ACSL2ASTTranslator.java
 * Content:     This class is in charge of translating the ACSL contract given as input into several elements, all
 * 				represented as internal ASTs:
 * 				- A list of helper methods that will be added at the end of the C file
 * 				- A list of structures that will be added at the beginning of the C file
 * 				- The portion of C code that will effectively replace the method call in the folded version of the
 * 				  program
 * 				This class only translates the methods/structures that are specific to the given contract, and does not
 * 				handle the "generic" ones (e.g., the "valid(void*, int, int)" method in charge of asserting the validity
 * 				of a given pointer in the given range).
 * 				Such "generic" methods/structures are handled separately by the TODO class.
 * 				Note also that this class creates the AST with the information contained in the function contract only.
 * 				It is thus improper for direct usage, as, for instance, the generated portion of C code will make use
 * 				of the parameters identifiers of the contract, instead of of the calling function.
 * 				This mapping is performed in a second phase by TODO class.
 * Author:      Quentin Nivon
 * Email:       quentin.nivon@uol.de
 * Creation:    31/03/26
 */

public class ACSL2ASTTranslator
{
	private final List<AbstractSyntaxTree> helperMethods;
	private final List<AbstractSyntaxTree> helperStructures;
	private final AbstractSyntaxTree functionFolding;

	//Constructors

	public ACSL2ASTTranslator()
	{
		this.helperMethods = new ArrayList<>();
		this.helperStructures = new ArrayList<>();
		this.functionFolding = new AbstractSyntaxTree(CFactory.createTranslationUnitNode());
	}

	//Public methods

	/**
	 * Main method if this class, which is in charge of translating the given ACSL contract into its corresponding
	 * pieces of C code, decomposed in helper methods, helper structures, and function folding.
	 */
	public void translate()
	{

	}

	public List<AbstractSyntaxTree> getHelperMethods()
	{
		return Collections.unmodifiableList(this.helperMethods);
	}

	public List<AbstractSyntaxTree> getHelperStructures()
	{
		return Collections.unmodifiableList(this.helperStructures);
	}

	public AbstractSyntaxTree getFunctionFolding()
	{
		return this.functionFolding;
	}

	//Private methods

	private void addTestHelperStructure()
	{
		final AbstractSyntaxTree abstractSyntaxTree = new AbstractSyntaxTree(CFactory.createSimpleDeclarationNode());
		final CompositeTypeSpecifierNode helperStructure = CFactory.createCompositeTypeSpecifierNode(CStorageClass.TYPEDEF);
		final String functionName = "my_function_name";

		//Set the name of the structure
		helperStructure.setName(functionName + "_old_values");

		//Add its components
		helperStructure.addComponent(new SimpleVariable(CType.UNSPECIFIED.setType("my_type_1"), "my_var_name_1"));
		helperStructure.addComponent(new SimpleVariable(CType.INT, "my_var_name_2"));

		//Connect the structure to the root node
		abstractSyntaxTree.getRoot().addChildAndForceParent(helperStructure);

		//Comment the structure
		((CBaseNode) abstractSyntaxTree.getRoot()).addComment(new CComment(
			CCommentType.MULTI_LINE,
			CCommentNature.REGULAR,
			-1,
			-1,
			String.format(
				"/*\n\tThis structure was generated by the ACSL2C translator. It aims at storing" +
				"\n\tthe old values of the parameters given to the \"%s\" function," +
				"\n\tin order to mimic the behaviour of the \"\\old(value)\" ACSL operator.\n*/",
				functionName
			)
		));

		this.helperStructures.add(abstractSyntaxTree);
	}

	//Sub-class

	public static class SimpleVariable {
		private final CType type;
		private final String name;

		SimpleVariable(final CType type,
					   final String name)
		{
			this.type = type;
			this.name = name;
		}

		public CType getType()
		{
			return this.type;
		}

		public String getName()
		{
			return this.name;
		}
	}
}
